### ISSUE TITLE
Exception on first run

### ISSUE THREAD

**Issue by jeena** [mhthies/ews-caldav-sync#2]
Hi,

I'm not sure what it means, but I got an exception the first time I ran it. I followed the readme instructions and got this:

```
(venv) ➜ jeena@William ews-caldav-sync (main) python3 ews_calendar_sync.py
Traceback (most recent call last):
  File "/home/jeena/Projects/ews-caldav-sync/venv/lib/python3.9/site-packages/exchangelib/ewsdatetime.py", line 272, in from_timezone
    return {
KeyError: 'pytz_deprecation_shim'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeena/Projects/ews-caldav-sync/ews_calendar_sync.py", line 36, in <module>
    ews_account = Account(config['ews']['account'], access_type=IMPERSONATION if config['ews']['impersonate'] else DELEGATE,
  File "/home/jeena/Projects/ews-caldav-sync/venv/lib/python3.9/site-packages/exchangelib/account.py", line 103, in __init__
    self.default_timezone = EWSTimeZone.localzone()
  File "/home/jeena/Projects/ews-caldav-sync/venv/lib/python3.9/site-packages/exchangelib/ewsdatetime.py", line 290, in localzone
    return cls.from_timezone(tz)
  File "/home/jeena/Projects/ews-caldav-sync/venv/lib/python3.9/site-packages/exchangelib/ewsdatetime.py", line 280, in from_timezone
    raise TypeError('Unsupported tzinfo type: %r' % tz)
TypeError: Unsupported tzinfo type: _PytzShimTimezone(zoneinfo.ZoneInfo(key='Asia/Seoul'), 'Asia/Seoul')
```
Any tips on what I can do here?

**Comment by mhthies** [comment]
Hi,
this is an upstream issue of exchangelib, caused by an update of the `tzlocal` library: https://github.com/ecederstrand/exchangelib/issues/1002
As far as I can see, they already [implemented a workaround](https://github.com/ecederstrand/exchangelib/pull/1003) but did not package it into a release yet.

From my understanding of the issue, you could try downgrading tzlocal to a 3.x version until exchangelib releases the fix.

**Comment by jeena** [comment]
I see, thanks for the tips, I'll try that.
